# Generated by Django 4.2 on 2025-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="avg_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
