# Generated by Django 4.2 on 2025-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_avg_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="avg_rating",
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
